name: Aliyun Docker Image CI

on:
  push:
    branches:
      - my-custom
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Aliyun Docker Registry
      uses: docker/login-action@v3
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIYUN_REGISTRY_USER }}
        password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

    - uses: actions/checkout@v3
    - name: Build and push the Docker image (lettaai)
      run: |
        # Extract the version number from pyproject.toml using awk
        CURRENT_VERSION=$(awk -F '"' '/version =/ { print $2 }' pyproject.toml | head -n 1)
        # Build the Docker image with two tags: versioned and latest
        docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_HUB_NAME }}/letta:$CURRENT_VERSION --tag registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_HUB_NAME }}/letta:latest
        # Push both the versioned and latest tags to Aliyun
        docker push registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_HUB_NAME }}/letta:$CURRENT_VERSION
        docker push registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_HUB_NAME }}/letta:latest